Repository apache/sedona-spatialbench, pull requests merged in 2025-09, with the labels that each got.

#19 docs: add overview and methodology
  docs/overview-methodology.md
Labels: documentation

#23 CI: fix caching and skip workflow runs for Markdown-only changes
  .github/workflows/rust.yml
Labels: github actions

#37 [DOCS] Update acknowledgements
  README.md
Labels: documentation

#38 docs: Fixes typos on SpatialBench homepage, fixes mobile nav black text, removes PostGIS line
  docs/index.md
  docs/single-node-benchmarks.md
  docs/stylesheets/extra.css
Labels: documentation

#42 [DOCS] Add SpatialBench Distributions doc
  docs/datasets-generators.md
  docs/spatialbench-distributions.md
  mkdocs.yml
Labels: documentation

#44 [DOCS] Add katex to render math equations
  docs/javascripts/katex.js
  docs/spatialbench-distributions.md
  mkdocs.yml
Labels: bug, documentation
